apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: app-naming-convention
spec:
  crd:
    spec:
      names:
        kind: AppNamingConvention
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package app_naming_convention

        violation[{"msg": msg}] {
          resource := input.review.object
          kind := resource.kind
          metadata := resource.metadata
          name := metadata.name
          team := split("_", name)[0]
          app := split("_", name)[1]
          env := split("_", name)[2]
          pattern := sprintf("^%s_%s_(dev|stg|prd)$", [team, app])
          not matched := not re_match(pattern, env)
          msg := sprintf("Invalid app naming convention: '%s'. Must be in the format '<Team_Name>_<App_Name>_(dev|stg|prd)'.", [name])
          not resource.kind == "Namespace"
          not metadata.namespace == "kube-system"
          not matched
        }
