apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcelimits.constraints.gatekeeper.sh
spec:
  group: constraints.gatekeeper.sh
  names:
    kind: resourcelimit
    plural: resourcelimits
    singular: resourcelimit
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              match:
                type: object
                properties:
                  kinds:
                    type: array
                    items:
                      type: object
                      properties:
                        apiGroups:
                          type: array
                          items:
                            type: string
                          x-kubernetes-list-map-keys:
                          - apiGroup
                        kinds:
                          type: array
                          items:
                            type: string
                          x-kubernetes-list-map-keys:
                          - kind
                required:
                - kinds
              parameters:
                type: object
                properties:
                  containerLimits:
                    type: object
                    properties:
                      requests:
                        type: object
                        additionalProperties:
                          type: string
                          pattern: ^[0-9]+(m|Mi|Gi|G|Ki|K)$
                        minProperties: 2
                      limits:
                        type: object
                        additionalProperties:
                          type: string
                          pattern: ^[0-9]+(m|Mi|Gi|G|Ki|K)$
                        minProperties: 2
                    required:
                    - requests
                    - limits
                required:
                - containerLimits
