apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredresources
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredResources
      validation:
        openAPIV3Schema:
          properties:
            cpu:
              type: string
              pattern: '^[0-9]+(m)?$'
            memory:
              type: string
              pattern: '^[0-9]+(Mi|Gi)?$'
          required: ['cpu', 'memory']
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredresources
        violation[{"msg": msg}] {
          resource := input.review.object
          cpuReq := resource.spec.containers[_].resources.requests.cpu
          memReq := resource.spec.containers[_].resources.requests.memory
          cpuLim := resource.spec.containers[_].resources.limits.cpu
          memLim := resource.spec.containers[_].resources.limits.memory
          cpuReq == "" or not cpuReq.re.match("^[0-9]+(m)?$") or cpuLim == "" or not cpuLim.re.match("^[0-9]+(m)?$") or
          memReq == "" or not memReq.re.match("^[0-9]+(Mi|Gi)?$") or memLim == "" or not memLim.re.match("^[0-9]+(Mi|Gi)?$") ->
            msg := sprintf("CPU and memory resources must be defined for all containers in the Deployment")
        }

